---
version: "3.1"
services:
  jellyfin:
    image: ghcr.io/confusedpolarbear/jellyfin-intro-skipper:10.8.5
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=13000
      - TZ=Europe/Amsterdam
    volumes:
      - ${ROOT_DIR}/docker/jellyfin-config:/config
      - ${ROOT_DIR}/data/media/tv:/data/tvshows
      - ${ROOT_DIR}/data/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:1.29.1
    container_name: plex
    network_mode: host
    environment:
      - PUID=${UID}
      - PGID=13000
      - VERSION=docker
    volumes:
      - ${ROOT_DIR}/docker/plex-config:/config
      - ${ROOT_DIR}/data/media/movies:/movies
      - ${ROOT_DIR}/data/media/tv:/tv
    restart: unless-stopped
  emby:
    image: emby/embyserver:latest
    container_name: embyserver
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
    volumes:
      - ${ROOT_DIR}/docker/emby-config:/config # Configuration directory
      - ${ROOT_DIR}/data/media/tv:/mnt/share1 # Media directory
      - ${ROOT_DIR}/data/media/movies:/mnt/share2 # Media directory
    ports:
      - 8097:8096 # HTTP port
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    restart: unless-stopped

#
# SERVARR
#
  radarr:
    image: lscr.io/linuxserver/radarr:4.2.4
    container_name: radarr
    networks:
      - vpn_connection
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/radarr-config:/config
      - ${ROOT_DIR}/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:3.0.9
    container_name: sonarr
    networks:
      - vpn_connection
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/sonarr-config:/config
      - ${ROOT_DIR}/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    network_mode: "service:vpn"
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/jackett-config:/config
      - ${ROOT_DIR}/data:/data
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:vpn"
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
    volumes:
      - ${ROOT_DIR}/docker/qbittorrent-config:/config
      - ${ROOT_DIR}/data/torrents:/data/torrents
    restart: unless-stopped

  vpn:
    image: thrnz/docker-wireguard-pia:latest
    container_name: vpn
    volumes:
        - ${ROOT_DIR}/docker/pia-config/pia:/pia
        - ${ROOT_DIR}/docker/pia-config/pia-shared:/pia-shared
    cap_add:
        - NET_ADMIN
        - SYS_MODULE
    environment:
        - LOC=swiss
        - USER=${VPN_USER}
        - PASS=${VPN_PWD}
        - LOCAL_NETWORK=192.168.178.0/24
    ports:
      - 9117:9117
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv6.conf.default.disable_ipv6=1
        - net.ipv6.conf.all.disable_ipv6=1
        - net.ipv6.conf.lo.disable_ipv6=1
    healthcheck:
        test: ping -c 1 www.google.com || exit 1
        interval: 30s
        timeout: 10s
        retries: 3

  #Cleans sonar torrents that are stale
  sonar-torrent-cleaner:
    restart: unless-stopped
    image: sonarr-torrent-cleaner
    container_name: sonar-torrent-cleaner
networks:
  vpn_connection: